{"cells":[{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"7KwHWuyowcua","executionInfo":{"status":"ok","timestamp":1709965021240,"user_tz":300,"elapsed":2046,"user":{"displayName":"Luis Stanley Jovel Portal","userId":"08916066368548829529"}},"outputId":"1191bb30-bb0f-4637-a6b6-4f8e1cfea64d"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n","/content/drive/MyDrive/Documents/Fulbright Application 2020-2021/Courses/Spring Semester 2024/Deep Decision and Reinforcement Learning/project\n"]}],"source":["# Load the Drive helper and mount\n","from google.colab import drive\n","drive.mount('/content/drive', force_remount=True)\n","%cd /content/drive/MyDrive/Documents/Fulbright\\ Application\\ 2020-2021/Courses/'Spring Semester 2024'/'Deep Decision and Reinforcement Learning'/project"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/","height":543},"executionInfo":{"elapsed":45937,"status":"error","timestamp":1709964420173,"user":{"displayName":"Luis Stanley Jovel Portal","userId":"08916066368548829529"},"user_tz":300},"id":"f7uCB7Crx66y","outputId":"1d6a2a3d-84bf-4882-fb7c-394042fbd42d"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["cuda\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-3-18c047ad4123>\", line 77, in <cell line: 77>\n","    for file in os.listdir(\"./demos\"):\n","OSError: [Errno 107] Transport endpoint is not connected: './demos'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-3-18c047ad4123>\", line 77, in <cell line: 77>\n","    for file in os.listdir(\"./demos\"):\n","OSError: [Errno 107] Transport endpoint is not connected: './demos'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-3-18c047ad4123>\", line 77, in <cell line: 77>\n","    for file in os.listdir(\"./demos\"):\n","OSError: [Errno 107] Transport endpoint is not connected: './demos'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["import os\n","import json\n","from enum import Enum\n","\n","import numpy as np\n","import torch\n","import torch.nn as nn\n","from torch.utils.data import DataLoader, random_split\n","from torch.optim.lr_scheduler import ReduceLROnPlateau\n","from tqdm import tqdm\n","\n","device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n","print(device)\n","\n","class MultiHistoryNetwork(nn.Module):\n","  def __init__(self, num_features, hidden_size, output_size, num_history):\n","    super(MultiHistoryNetwork, self).__init__()\n","    self.lstm = nn.LSTM(num_features, hidden_size, num_layers=1, batch_first=True)\n","    self.output_features = hidden_size * num_history\n","    self.linear = nn.Sequential(\n","        nn.Linear(self.output_features, self.output_features),\n","        nn.ReLU(),\n","        nn.Linear(self.output_features, 512),\n","        nn.ReLU(),\n","        nn.Linear(512, 128),\n","        nn.ReLU(),\n","        nn.Linear(128, output_size),\n","        nn.Tanh()\n","    )\n","\n","  def forward(self, x):\n","    # x is of shape (batch_size, num_history, num_features)\n","    x, _ = self.lstm(x)  # Pass through LSTM\n","    x = x.reshape(x.size(0), -1)  # Reshape to remove sequence dimension\n","    x = self.linear(x)\n","    return x\n","\n","class Constants(Enum):\n","    INPUT_SIZE = 25  # Number of features in observation\n","    HIDDEN_SIZE = 256  # Number of units in hidden layer\n","    NUM_HISTORY = 5  # Number of history steps to use\n","    OUTPUT_SIZE = 2  # Number of actions\n","    DROPOUT = 0.25  # Dropout rate\n","    lr = 1e-3  # Learning rate\n","    EPOCHS = 20  # Number of epochs to train\n","\n","    NUM_LAYERS = 4  # Number of LSTM layers\n","\n","class Dataset(torch.utils.data.Dataset):\n","    def __init__(self, obs_list, action_list, num_history):\n","        self.obs_list = obs_list\n","        self.action_list = action_list\n","        self.num_history = num_history\n","\n","    def __len__(self):\n","        return len(self.obs_list)\n","\n","    def __getitem__(self, idx):\n","        obs = self.obs_list[idx]\n","        action = self.action_list[idx]\n","\n","        # Retrieve history observations\n","        start_idx = max(0, idx - self.num_history)\n","        history_obs = self.obs_list[start_idx:idx]\n","\n","        # Pad history observations if necessary\n","        if len(history_obs) < self.num_history:\n","            pad_width = self.num_history - len(history_obs)\n","            padding = torch.zeros(pad_width, Constants.INPUT_SIZE.value)\n","            history_obs = torch.cat([padding, history_obs])\n","\n","        return history_obs, action\n","\n","obs_list = torch.tensor([])\n","action_list = torch.tensor([])\n","\n","for file in os.listdir(\"./demos\"):\n","    if file.startswith(\"*\") or file.startswith(\".\"):\n","        continue\n","    with open(f\"./demos/{file}\", \"r\") as f:\n","        data = json.load(f)\n","        for episode in data:\n","            min_length = min(len(episode[0]), len(episode[1]))\n","            obs = episode[0][:min_length]\n","            action = episode[1][:min_length]\n","\n","            if len(obs) == 0 or len(action) == 0:\n","                continue\n","\n","            obs = torch.tensor(obs, dtype=torch.float32)\n","            action = torch.tensor(action, dtype=torch.float32)\n","            obs_list = torch.cat([obs_list, obs])\n","            action_list = torch.cat([action_list, action])\n","\n","dataset = Dataset(obs_list, action_list, Constants.NUM_HISTORY.value)\n","train_size = int(0.8 * len(dataset))\n","test_size = len(dataset) - train_size\n","train_dataset, test_dataset = random_split(dataset, [train_size, test_size])\n","\n","train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)\n","test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False)\n","\n","# Instantiate model, loss function, and optimizer\n","# model = FNN(\n","model = MultiHistoryNetwork(\n","    Constants.INPUT_SIZE.value,\n","    # Constants.INPUT_SIZE.value * Constants.NUM_HISTORY.value,\n","    Constants.HIDDEN_SIZE.value,\n","    Constants.OUTPUT_SIZE.value,\n","    Constants.NUM_HISTORY.value).to(device)\n","    # Constants.DROPOUT.value)\n","\n","# create a loss function\n","loss_fn = nn.MSELoss().to(device)\n","\n","# create an optimizer\n","optimizer = torch.optim.Adam(model.parameters(), lr=Constants.lr.value)\n","scheduler = ReduceLROnPlateau(optimizer, \"min\", patience=2)\n","# train the model\n","iterator = tqdm(range(Constants.EPOCHS.value), total=Constants.EPOCHS.value, desc=\"Training\")\n","\n","for epoch in iterator:\n","    model.train()\n","    iterator.set_description(\"Training\")\n","    for obs, action in train_dataloader:\n","        optimizer.zero_grad()\n","        obs = obs.to(device)\n","        action = action.to(device)\n","        pred = model(obs)\n","        loss = loss_fn(pred, action)\n","        loss.backward()\n","        optimizer.step()\n","\n","    # evaluate the model\n","    iterator.set_description(\"Evaluating\")\n","    model.eval()\n","    with torch.no_grad():\n","        test_loss = 0\n","        for obs, action in test_dataloader:\n","            obs = obs.to(device)\n","            action = action.to(device)\n","            pred = model(obs)\n","            test_loss += loss_fn(pred, action).item()\n","        test_loss /= len(test_dataloader)\n","    # iterator.set_postfix(epoch=epoch, loss=test_loss)\n","    print('epoch: ', epoch, 'loss: ', test_loss)\n","    scheduler.step(test_loss)\n","\n","# save the model\n","torch.save(model, \"model.pt\")"]}],"metadata":{"accelerator":"GPU","colab":{"gpuType":"T4","provenance":[],"authorship_tag":"ABX9TyOnatImE7NMWC7EbxDoWXr+"},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}